management:
  context-path: /admin
  security:
    enabled: false
  info:
    git:
      mode: full

server:
  port: 8080

filter:
  version: 1.0
  definition:
    filename: /data/filterDefinition.properties
  empty:
    message:
      feedback: I hate emtpy strings on dev-local!

info:
  custom:
    env: dev-local
    message: rancher rulez
