management:
  context-path: /admin
  security:
    enabled: false
  info:
    git:
      mode: simple

server:
  port: 8080

filter:
  version: 1.0
  definition:
    filename: /data/env/prod/filterDefinition.properties
  empty:
    message:
      feedback: I hate emtpy strings in production!

info:
  custom:
    env: prod
    message: rancher rulez
