version: '3.3'

services:

  frontend:
    image: looztra/guestbook-frontend:0.6.0-aio
    ports:
      - "8000:80"

  gateway:
    image: looztra/guestbook-gateway:0.6.0-aio
    ports:
      - "8080:8080"
    environment:
      GATEWAY_GUESTBOOK_ENDPOINTSASSTRING: "storage:8080"
      GATEWAY_FILTER_ENDPOINTSASSTRING: "filter:8080"
    depends_on:
      - storage
      - filter

  filter:
    image: guestbook-filter
    ports:
      - "8086:8080"
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}

  storage:
    image: looztra/guestbook-storage:0.6.0-aio
    ports:
      - "8085:8080"
    environment:
      GUESTBOOK_BACKEND_REDIS_READ_VIP: redis
      GUESTBOOK_BACKEND_REDIS_WRITE_VIP: redis
    depends_on:
      - redis

  redis:
    image: redis:3-alpine
